### ISSUE TITLE
inline and resolve

### ISSUE THREAD

**Issue by Diokuz** [postcss/postcss-url#104]
I want to inline all files under `4 kb` and resolve all others. How can I do that?

I mean this one

```css
.cls1 {
  background-image: url('small-image.png');
}
.cls2 {
  background-image: url('big-image.png');
}
```

should transform to

```css
.cls1 {
  background-image: url('base64...');
}
.cls2 {
  background-image: url('/Users/.../project/src/images/big-image.png');
}
```
My options object looks like

```js
{
  url: 'inline',
  maxSize: 4,
  fallback: 'rebase'
}
```

But nothing happens for big files.
