### ISSUE TITLE
asset paths wont work in @import files

### ISSUE THREAD

**Issue by digitalkaoz** [postcss/postcss-url#120]
hey,

here a tiny setup:

```scss
//main.scss

@import "deps/foo"

#bar {
  background: url(./img/bar.jpg)
}
```

```scss
//deps/foo.scss
#foo {
  background: url(../img/foo.jpg)
}
```

if i use this config:

```js
{
            url: "inline",
            maxSize: 10,
            optimizeSvgEncode: true,
            fallback: "copy",
            assetsPath: "./dist_img",
            shrink: 8,
            useHash: true,
            hashOptions: {
                append: true
            }
        }
```

`#bar` works fine, the image is copied
`#foo` does not because the import is somehow resolved to `main.scss` and the defined path `../img/foo.jpg` doesnt match anymore...

anyone has an idea?
