### ISSUE TITLE
Ignoring hashes

### ISSUE THREAD

**Issue by iamvdo** [postcss/postcss-url#23]
In `processDecl`, you ignore url with hashes. What is the reason ?

I have a problem with `@font-face` urls that contains hashes. For example, from font-awesome.css:

```css
@font-face {
  font-family: 'FontAwesome';
  src: url('../fonts/fontawesome-webfont.eot?v=4.3.0');
  src: url('../fonts/fontawesome-webfont.eot?#iefix&v=4.3.0') format('embedded-opentype'), url('../fonts/fontawesome-webfont.woff2?v=4.3.0') format('woff2'), url('../fonts/fontawesome-webfont.woff?v=4.3.0') format('woff'), url('../fonts/fontawesome-webfont.ttf?v=4.3.0') format('truetype'), url('../fonts/fontawesome-webfont.svg?v=4.3.0#fontawesomeregular') format('svg');
  font-weight: normal;
  font-style: normal;
}
```
