### ISSUE TITLE
Bug with whitespaces

### ISSUE THREAD

**Issue by andrewblond** [postcss/postcss-url#26]
If you use whitespaces in url, it will be incorrectly rebase.

```
.
├── dir
│   ├── imported.css
│   └── img.png
└── styles.css
```

`dir/imported.css`

```css
.imported {
    background: url( "img.png" );
}
```

`styles.css`

```css
@import "dir/imported.css";
```

After the file `styles.css` is processed will get result.

Actual:

```css
.imported {
    background: url(dir/ "img.png" );
}
```

Expected:

```css
.imported {
    background: url("dir/img.png");
}
```
