### ISSUE TITLE
copy assets to specified directory?

### ISSUE THREAD

**Issue by zoubin** [postcss/postcss-url#34]
Right now we can specify `assetPath`, which determines the value or `url(value)` in css, and the destination of the copied asset will be calculated based on this info.
That is very convenient if we want to specify a `url(value)` in css.

I am handling cases where the value in `url(value)` does not matter as long as it is right, but the destination of the copied asset does.

Here is an example.

css file `/path/to/src/page/index/index.css`:
```css
.sp-icon {
  background-image: url(i/sp-icon.png);
}
```
the asset file is `/path/to/src/page/index/i/sp-icon.png`

I want to build css to `/path/to/build/page/index/index.css`, and the sprite to `/path/to/build/sp/sp-icon.png`.

So, in  `/path/to/build/page/index/index.css`, it looks like:

```css
.sp-icon {
  background-image: url(../../sp/sp-icon.png);
}
```

Any idea how to achieve this?
