### ISSUE TITLE
{url: "copy"} puts backslashes in URLs when run on Windows

### ISSUE THREAD

**Issue by akrawitz** [postcss/postcss-url#47]
On Windows, start with this in _src/index.css_:

``` css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: normal;
  src: url(resources/fonts/Roboto-normal-400.woff) format('woff');
}
```

Run this on it:

``` javascript
gulp.task("build-css", function () {
    return gulp.src('src/index.css')
        .pipe(gulpPostcss([
            postcssUrl({url: 'copy'})
        ], {to: 'dest/index.css'}))
        .pipe(gulp.dest('dest'));
});
```

And _dest/index.css_ will end up with this:

``` css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: normal;
  src: url(resources\fonts\Roboto-normal-400.woff) format('woff');
}
```

The problem is in the last line of `processCopy()`:

``` javascript
return createUrl(urlMeta, path.join(relativeAssetsPath, nameUrl))
```

This is creating a URL from a file path and assuming that they both use '/' as the separator. A fix would be to follow `processRebase()` and convert the '\' separators to '/':

``` javascript
var assetPath = path.join(relativeAssetsPath, nameUrl)
if (path.sep === "\\") {
    assetPath = assetPath.replace(/\\/g, "\/")
}  
return createUrl(urlMeta, assetPath)
```
