### ISSUE TITLE
{url: "copy"} mishandles spaces in file paths

### ISSUE THREAD

**Issue by akrawitz** [postcss/postcss-url#48]
Lets say I have a project in _C:\My Projects\project_. And within that, I have these source files:

```
src/
    index.css
    fonts/
        myfont.woff
```

And _index.css_ looks like this:

``` css
@font-face {
  font-family: 'myfont';
  font-style: normal;
  font-weight: normal;
  src: url(fonts/myfont.woff) format('woff');
}
```

And I want to create the following output:

```
dest/
    index.css
    fonts/
        myfont.woff
```

So I run the following:

``` javascript
gulp.task("build", function () {
    return gulp.src('src/index.css')
        .pipe(gulpPostcss([postcssUrl({url: 'copy'})], {to: 'dest/index.css'}))
        .pipe(gulp.dest('dest'));
});
```

I get the error message:
`postcss-url: C:\My Projects\project\src\index.css:5:3: Can't read file '/My%20Projects/projects/src/fonts/myfont.woff', ignoring`

The problem is with line 299 of _index.js_ in `processCopy()`:
`var fileLink = url.parse(filePathUrl, true)`
This is parsing filePathUrl as if it were a URL, when it is actually a file path, which is leading to the incorrect encoding of spaces, and to the dropping of the leading 'C:\'.
