### ISSUE TITLE
Trouble when using postcss-url only in production mode

### ISSUE THREAD

**Issue by ahtohbi4** [postcss/postcss-url#56]
I have a project with source files:
```
index.html
css/
    style.css
img/
    picture.png
```
In developers mode i want to see URL to the images files:
```css
/* dev mode */
.some-class {
    background: url(/img/picture.png);
}
```
It is very usefull to debugging.
At the same time in production mode I wish to have base64 encoded images.
```css
/* prod mode */
.some-class {
    background: url(data:image/png;base64,...);
}
```
But, according to function [isUrlShouldBeIgnored](https://github.com/postcss/postcss-url/commit/6b4893429e377d1175486170ec2b40e005be882b#diff-168726dbe96b3ce427e7fedce31bb0bcR146), URLs starting with '/' are ignored.
