### ISSUE TITLE
Ignoring absolute file references.

### ISSUE THREAD

**Issue by DylanPiercey** [postcss/postcss-url#69]
My config:

``` js
{
    url: 'inline',
    basePath: './client'
}
```

``` css
body {
    background: url('/img/test.png');
}
```

I would expect that the test image would be inlined however https://github.com/postcss/postcss-url/blob/master/index.js#L163 prevents this.

I would rather not use relative urls in my css file.
