### ISSUE TITLE
Absolute URLs?

### ISSUE THREAD

**Issue by stevenvachon** [postcss/postcss-url#80]
```css
element {
  property: url(path/to/file.ext);
}
```
```js
postcss()
.use( url({ url:"rebase" }) )
.process(css, {
  from: "/Users/me/project/",
  to: "http://cdn/"
});
```

doesn't transform anything

**Comment by sergcen** [comment]
you should use custom url function, see [readme](https://github.com/postcss/postcss-url#muiltiple-options)

**Comment by stevenvachon** [comment]
That's how I ended up doing it, but now with 6.x, the function isn't even being called.

**Comment by sergcen** [comment]
@stevenvachon, are you using array of options? had a problem with it, and fixed yesterday

**Comment by stevenvachon** [comment]
Nope:
```js
const options = { url:function(){ console.log(arguments) } }
``

When I revert to 5.x, the function gets called.

**Comment by sergcen** [comment]
hmm... it's should work, working in tests and own project
can you show css example?

**Comment by stevenvachon** [comment]
```css
@font-face {
  font-family: fake;
  font-style: normal;
  font-weight: 400;
  src: url("/Users/stevendvachon/BatchBlue/mashapp-email-templates/test/fixtures/fonts/fake.woff2") format("woff2"), url("/Users/stevendvachon/BatchBlue/mashapp-email-templates/test/fixtures/fonts/fake.woff") format("woff");
  }
  body {
  background-color: #123456;
  font-family: fake;
  }
  #id {
  color: #654321;
  }
  .class {
  color: black;
  }
  .class:hover {
  color: white;
  }
  .unused {
  color: green;
  }
  @media screen {
  .unused-too {
  color: green;
  }
  }
```
