### ISSUE TITLE
dir.file incorrect when stacking multiple backgrounds

### ISSUE THREAD

**Issue by kevinkace** [postcss/postcss-url#96]
Using `postcssUrl({ url : (asset, dir) => {} });`

This works:
```css
/* ./public/css/index.css */
div {
    background: url(./img/bg.jpg);
}
```
```js
// dir
{
    from: '.',
    to: '.',
    file: 'd:\\app\public\css'
}
```

This does not:
```css
/* ./public/css/index.css */
div {
    background: url(./img/bg.jpg), linear-gradient(to right, red 0%, black 100%);
}
```
```js
// dir
{
    from: '.',
    to: '.',
    file: 'd:\\app\public'
}
```

Expected: same as single BG.
